from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException

# Import NLP service functions from backend/nlp/service.py.
try:
    from backend.nlp.service import (
        get_employee_nlp,
        get_executive_summary,
        get_npi_distribution,
        get_sentiment_summary,
        get_strategic_summary,
        get_topic_summary,
    )
except ImportError:
    # Fallback import for runtimes where backend is already the Python root.
    from nlp.service import (  # type: ignore
        get_employee_nlp,
        get_executive_summary,
        get_npi_distribution,
        get_sentiment_summary,
        get_strategic_summary,
        get_topic_summary,
    )


router = APIRouter(prefix="/api/nlp", tags=["nlp"])


@router.get("/summary")
def get_nlp_summary() -> dict[str, Any]:
    """Return NLP summary including sentiment, topics, and NPI distribution."""
    sentiment_payload = get_sentiment_summary()
    topic_payload = get_topic_summary()
    npi_payload = get_npi_distribution()

    return {
        "sentiment": sentiment_payload,
        "topic": topic_payload,
        "npi_distribution": npi_payload,
    }


@router.get("/executive")
def get_nlp_executive_summary(lang: str = "en") -> dict[str, Any]:
    """Return executive summary generated by the NLP pipeline."""
    return get_executive_summary(lang)


@router.get("/strategic-summary")
def get_nlp_strategic_summary() -> dict[str, Any]:
    """Return strategic-level NLP + ML analytics."""
    return get_strategic_summary()


@router.get("/employee/{employee_id}")
def get_employee_nlp_profile(employee_id: str) -> dict[str, Any]:
    """Return full NLP profile for a specific employee."""
    payload = get_employee_nlp(employee_id)

    # Return 404 when employee does not exist while keeping JSON-serializable detail.
    if payload.get("status") == "not_found":
        raise HTTPException(status_code=404, detail=payload)

    return payload
